### ISSUE TITLE
Incompatibility with flaky?

### ISSUE THREAD

**Issue by bilderbuchi** [ChrisBeaumont/smother#11]
Hi!

I am currently playing around with testing [hypothesis](https://github.com/HypothesisWorks/hypothesis-python) with smother (see HypothesisWorks/hypothesis-python#852), and seem to (apparently) run into problems because hypothesis uses [flaky](https://github.com/box/flaky), many tests fail with "TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'" in `control.py:70`, e.g.
```
___________ ERROR at teardown of test_errors_when_asked_for_example ___________
C:\Continuum\Anaconda3\envs\hypothesis_test\lib\site-packages\flaky\flaky_pytest_plugin.py:271: in <lambda>
    lambda: ihook(item=item, **kwds),
..\smother\smother\pytest_plugin.py:63: in pytest_runtest_teardown
    self.smother.save_context(item.nodeid)
..\smother\smother\control.py:70: in save_context
    for key, val in self.coverage.collector.data.items()
..\smother\smother\control.py:70: in <dictcomp>
    for key, val in self.coverage.collector.data.items()
E   TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```

Do you have an idea what's going wrong here?

**Comment by ChrisBeaumont** [comment]
Hm I think flaky is a red herring here, and the real issue is that you are running coverage with branch coverage. Have you tried using the (unmerged) patch from #8?

**Comment by bilderbuchi** [comment]
Ha, that could be it. Trying the patch from #8 was next on my to-do list, so I'll give that a shot.

**Comment by bilderbuchi** [comment]
OK, it seems this was indeed connected to branch coverage - after checking out #8, and running the hypothesis tests, I get a different message:
```
__________________ ERROR at setup of test_prints_on_failure ___________________
C:\Continuum\Anaconda3\envs\hypothesis_test\lib\site-packages\flaky\flaky_pytest_plugin.py:271: in <lambda>
    lambda: ihook(item=item, **kwds),
tests\conftest.py:73: in validate_lack_of_trace_function
    assert sys.gettrace() is None
E   assert <coverage.CTracer object at 0x00000262E5609538> is None
E    +  where <coverage.CTracer object at 0x00000262E5609538> = <built-in function gettrace>()
E    +    where <built-in function gettrace> = sys.gettrace
```
It seems flaky doesn't like someone else having a trace function active?

**Comment by ChrisBeaumont** [comment]
The offending assertion is actually hypothesis code, not flaky code (`tests/conftests.py`, in `validate_lack_of_trace_function`). If I turn that function into a no-op, smother seems to run ok with #8 applied and invoked as `py.test tests/cover --smother=hypothesis --durations=0 -n 0`

**Comment by bilderbuchi** [comment]
flaky having been a red herring, this issue should be closed.
